chore(rpi): add install script
sebastien-lb/alfred-brain pull request #45
Opened 2019-02-20 16:06 UTC by sebastien-lb

2019-02-20 16:15 UTC, clementdessoude requested changes

2019-02-20 16:15 UTC, clement26695 commented on install_rpi.sh
> +echo Deleting previous folder
Test if exist and ask if you want to delete them ?

2019-02-20 16:15 UTC, clement26695 commented on install_rpi.sh
> +    echo "nodejs not found, installing it"
ask for installation ?

2019-02-20 16:15 UTC, clement26695 commented on install_rpi.sh
> +cd $BRAIN_FOLDER
```suggestion
cd ../$BRAIN_FOLDER
``` 
Merge two lines in one ?

2019-02-20 16:15 UTC, clement26695 commented on install_rpi.sh
> +python -m venv .
Fail if python is not installed

2019-02-20 16:15 UTC, clement26695 commented on install_rpi.sh
> +python -m venv .
I would rather use 
```suggestion
python -m venv venv
```
to keep all the virtualenv files in one folder instead of mixing them with the source code

2019-02-20 16:15 UTC, clement26695 commented on install_rpi.sh
> +source ./bin/activate
if previous change is accepted, change to 
```suggestion
source venv/bin/activate
```

2019-02-20 16:15 UTC, clement26695 commented on install_rpi.sh
> +
deactivate virtualenv ?

2019-02-21 13:17 UTC, sebastien-lb commented on install_rpi.sh
> +python -m venv .
On l'installe juste au dessus non?

2019-02-21 13:17 UTC, sebastien-lb commented on install_rpi.sh
> +echo Deleting previous folder
Done

2019-02-21 13:18 UTC, sebastien-lb commented on install_rpi.sh
> +    echo "nodejs not found, installing it"
bof, pas envie :)

2019-02-21 13:23 UTC, clement26695 commented on install_rpi.sh
> +python -m venv .
Where ? Tu n'affiche pas juste un message si python n'est pas installé ?

https://github.com/sebastien-lb/alfred-brain/blob/b58335f6434c42680f6a35bf6cf3e00d79eb44be/install_rpi.sh#L59-L70

2019-02-21 13:24 UTC, clement26695 commented on install_rpi.sh
> +    echo "nodejs not found, installing it"
As you want !

2019-02-21 13:27 UTC, sebastien-lb commented on install_rpi.sh
> +python -m venv .
ah oui oups !

2019-02-21 14:00 UTC, clementdessoude approved these changes

2019-02-21 14:50 UTC, merged